/**
 * Tenant context via Node AsyncLocalStorage (PRD F-8, 决定 #4).
 *
 * WHY: the ADK search agent is a lazily-built singleton and its tool
 * parameters are generated by the LLM. A tool argument is therefore
 * attacker-influencable — the store id must NEVER travel through the LLM.
 * Instead the API entrypoint (`/api/search`) resolves the store from the
 * `x-store-slug` request header and wraps the whole agent run in
 * `runWithTenant()`. Executors deep inside the call chain (vector/text
 * search in lib/agents/tools-b.ts) read it back with `getTenantStoreId()`.
 *
 * Short, explicit call chains (shelf-save, ops) take a plain `storeId`
 * parameter instead — ALS is only for paths that cross the LLM boundary.
 *
 * SECURITY: `getTenantStoreId()` throws when no context is set. Retrieval
 * fails closed — a missing tenant produces an error, never an unfiltered
 * cross-store query.
 */

import { AsyncLocalStorage } from 'node:async_hooks';

interface TenantContext {
  /** The store slug (== `store_id` on every tenant-scoped document). */
  storeId: string;
}

const tenantStorage = new AsyncLocalStorage<TenantContext>();

/** Run `fn` with the given store as the ambient tenant. */
export function runWithTenant<T>(storeId: string, fn: () => T): T {
  return tenantStorage.run({ storeId }, fn);
}

/** Ambient tenant store id. THROWS if called outside runWithTenant (fail closed). */
export function getTenantStoreId(): string {
  const ctx = tenantStorage.getStore();
  if (!ctx?.storeId) {
    throw new Error(
      'Tenant context missing — data access attempted outside runWithTenant(). ' +
      'Wrap the request entrypoint (see app/api/search/route.ts).'
    );
  }
  return ctx.storeId;
}

/** Ambient tenant store id, or null when not inside a tenant scope. */
export function getTenantStoreIdOrNull(): string | null {
  return tenantStorage.getStore()?.storeId ?? null;
}
